### PR TITLE
Added Typescript Definitions

### PR DESCRIPTION
**Pull request by PaitoAnderson**
Not sure if you are interested in supporting Typescript users...but this could really help some of us. Thanks!

### CODE REVIEW

**Comment by maxkordiyak** [comment]
Thank you for implementing!

**Comment by maxkordiyak** [comment]
I would like to re-implement this component using Typescript internally but now I don't have time to do this. Also instead of passing custom styles which looks not clean to me, I would maybe prefer passing custom components and wire them together inside

**Comment by PaitoAnderson** [comment]
@maxkordiyak That would be awesome, thanks for sharing your thoughts.

Just started looking at this library today, and might do a couple more PRs based on what I'm seeing.

1) Extacting `utils/api/index.js` as right now it is expecting a single query string parameter called `search`, and some a `data` and `success` properties in the result which isn't that flexible.
2) The placeholder is still showing as I type, not sure why yet.

Screen Shot 2019-07-30 at 10 33 28 AM

Cool?

**Comment by maxkordiyak** [comment]
Yes, please go ahead, it would be great to improvements. Again, thanks for contributing!

**Pull request merged**
